baseurl = "http://jogrammer.com/"
languageCode = "en-us"
title = "Jogrammer"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "beautifulhugo"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Joanna Lien"
    site_description = "Joanna's Programming Blog."
    location = "United States"
    # Link custom assets relative to /static
    avatar = "img/profile.jpg"
    header_background = "img/desk.jpg"
    header_title = "Let's get Jogramming!"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = "joanna-lien-8200742a"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "jlien86"
    gplus     = ""
